name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-image-name:latest .
        docker push your-dockerhub-username/your-image-name:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 using CodeDeploy
      uses: aws-actions/aws-codedeploy-deploy@v1
      with:
        application-name: ${{ secrets.AWS_DEPLOY_APPLICATION_NAME }}
        deployment-group-name: ${{ secrets.AWS_DEPLOY_DEPLOYMENT_GROUP }}
        deployment-config-name: CodeDeployDefault.OneAtATime
        description: "Deployment from GitHub Actions"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
