name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: usigmoid/cicd-github:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: Upload AppSpec file to S3
        run: |
          aws s3 cp appspec.yaml s3://codepipeline-ap-south-1-847405426361/appspec.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "${{ secrets.AWS_DEPLOY_APPLICATION_NAME }}" \
            --deployment-group-name "${{ secrets.AWS_DEPLOY_DEPLOYMENT_GROUP }}" \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --description "Deployment from GitHub Actions" \
            --revision locationType=S3,s3Location={bucket=codepipeline-ap-south-1-847405426361,key=appspec.yaml,bundleType=YAML} \
            --region "${{ secrets.AWS_REGION }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
